diff -urN spyder-3.2.3.orig/spyder/app/start.py spyder-3.2.3/spyder/app/start.py
--- spyder-3.2.3.orig/spyder/app/start.py	2017-09-24 20:14:45.562406430 -0400
+++ spyder-3.2.3/spyder/app/start.py	2017-09-24 20:19:56.652506350 -0400
@@ -1,5 +1,16 @@
 # -*- coding: utf-8 -*-
 
+# Hack for Python 2, linux-64 (maybe more?)
+# You can get a (probable) double free() deep in zeromq's TCP socket code:
+# *** Error in `/home/pwang/anaconda2-5/bin/python': free(): invalid pointer: 0x00007fe9b3fffb80 ***
+# ../../../../../libzmq.so.5.1.2(_ZN3zmq13tcp_address_t9to_stringERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xb8)[0x7f29d2be46c8]
+# ../../../../../libzmq.so.5.1.2(_ZN3zmq14tcp_listener_t11set_addressEPKc+0x61)[0x7f29d2be82c1]
+# ../../../../../libzmq.so.5.1.2(_ZN3zmq13socket_base_t4bindEPKc+0x58e)[0x7f29d2bd533e]
+# Importing it very early seems to avoid this problem.
+# Other projects have run into similar issues:
+# https://github.com/pytorch/pytorch/issues/2507
+import zmq
+
 # Std imports
 import os
 import os.path as osp
